RestaurantBackendWebsite/Models/EFModels/Meal.cs
namespace RestaurantBackendWebsite.Models.EFModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Meal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meal()
        {
            CartItemDetails = new HashSet<CartItemDetail>();
            OrderItemDetails = new HashSet<OrderItemDetail>();
        }

        public int Id { get; set; }

        [Required]
        [StringLength(50)]
        public string Name { get; set; }

        public int CategoryId { get; set; }

        public int Price { get; set; }

        public bool Status { get; set; }

        [StringLength(3000)]
        public string Description { get; set; }

        [Required]
        [StringLength(50)]
        public string MealsImage { get; set; }

        public DateTime CreatedDate { get; set; }

        public DateTime? ModifiedDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItemDetail> CartItemDetails { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItemDetail> OrderItemDetails { get; set; }
    }
}

RestaurantBackendWebsite/Controllers/MealsController.cs
using RestaurantBackendWebsite.Infra.FileValidators;
using RestaurantBackendWebsite.Infra;
using RestaurantBackendWebsite.Models.EFModels;
using RestaurantBackendWebsite.Models.ViewModels;
using RestaurantBackendWebsite.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using static RestaurantBackendWebsite.Repositories.MealsRepository;

namespace RestaurantBackendWebsite.Controllers
{
    public class MealsController : Controller
    {
		private AppDbContext db = new AppDbContext();
		// GET: Meals
		[Authorize]
		public ActionResult Index(string CategoryId, string name, int pageIndex = 0)
		{
			//List<MealIndexVM> vms = new MealsRepository().GetMeals();
			int pageSize = 10;
			var pagedProducts = new MealsRepository().GetPagedMeals(name, pageSize, pageIndex);

			ViewBag.PaginationInfo = new PaginationInfo(pagedProducts.PageSize, pagedProducts.PageIndex, pagedProducts.Total);
			ViewBag.criteria = name;

			return View(pagedProducts.Data);
		}


		// GET: Meals/Create
		[Authorize]
		public ActionResult Create()
		{
			ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
			return View();
		}

		// POST: Meals/Create
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create(MealIndexVM vm, HttpPostedFileBase myfile)
		{
			//將上傳檔案到/MyRestaurantImg 資料夾下

			string fileName;
			string path = Server.MapPath("~/MyRestaurantImg/");
			IFileValidator[] validators = new IFileValidator[]
			{
				new FileRequired(),
				new ImageValidator(),
				new FileSizeValidator(4096),
			};
			try
			{
				fileName = UploadFileHelper.Save(myfile, path, validators);

				//copy 一份到前台網站的資料夾下
				string sourceFilePath = Path.Combine(path, fileName);

				string dest = System.Configuration.ConfigurationManager.AppSettings["MealImgPath"];
				string destFilePath = Path.Combine(dest, fileName);

				System.IO.File.Copy(sourceFilePath, destFilePath, true);
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("myfile", ex.Message);

				ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", vm.CategoryId);
				return View(vm);
			}

			vm.MealsImage = fileName;



			if (ModelState.IsValid)
			{
				try
				{
					CreateMeals(vm);
				}
				catch (Exception ex)
				{
					ModelState.AddModelError("", ex.Message);
				}
			}
			if (ModelState.IsValid)
			{
				return RedirectToAction("Index");
			}
			return View(vm);

		}
		private void CreateMeals(MealIndexVM vm)
		{
			var meals = new Meal
			{
				CategoryId = vm.CategoryId,
				Name = vm.Name,
				Description = vm.Description,
				Price = vm.Price,
				MealsImage = vm.MealsImage,
				Status = vm.Status,
				CreatedDate = DateTime.Now,
				ModifiedDate = DateTime.Now,
			};
			db.Meals.Add(meals);
			db.SaveChanges();
		}

		// GET: Meals/Edit/5
		[Authorize]
		public ActionResult Edit(int? id)
		{

			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Meal meal = db.Meals.Find(id);
			if (meal == null)
			{
				return HttpNotFound();
			}
			ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", meal.CategoryId);

			var vm = new MealIndexVM
			{
				Id = meal.Id,
				CategoryId = meal.CategoryId,
				Name = meal.Name,
				Description = meal.Description,
				Price = meal.Price,
				MealsImage = meal.MealsImage,
				Status = meal.Status,
				CreatedDate = meal.CreatedDate,

			};

			return View(vm);
		}
		//POST: Meals/Edit/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Edit(MealIndexVM vm, HttpPostedFileBase myfile)
		{

			var mealInDb = db.Meals.Find(vm.Id);
			mealInDb.CategoryId = vm.CategoryId;
			mealInDb.Name = vm.Name;
			mealInDb.Description = vm.Description;
			mealInDb.Price = vm.Price;
			mealInDb.Status = vm.Status;
			mealInDb.ModifiedDate = DateTime.Now;

			//string fileName;
			//string fileName=mealInDb.MealsImage;//原本的圖片

			if (myfile != null && myfile.ContentLength > 0)
			{
				string fileName;
				//使用新上傳的檔案
				string path = Server.MapPath("~/MyRestaurantImg/");
				IFileValidator[] validators = new IFileValidator[]
				{
					//new FileRequired(),
					new ImageValidator(),
					new FileSizeValidator(4096),
				};
				//ViewModels的值要等於新值
				try
				{
					// 刪除舊圖片
					string oldFileName = Path.Combine(path, mealInDb.MealsImage);
					if (System.IO.File.Exists(oldFileName))
					{
						System.IO.File.Delete(oldFileName);
					}
					fileName = UploadFileHelper.Save(myfile, path, validators);


					//copy 一份到前台網站的資料夾下
					string sourceFilePath = Path.Combine(path, fileName);

					string dest = System.Configuration.ConfigurationManager.AppSettings["MealImgPath"];
					string destFilePath = Path.Combine(dest, fileName);

					System.IO.File.Copy(sourceFilePath, destFilePath, true);

					mealInDb.MealsImage = fileName;

				}
				catch (Exception ex)
				{
					ModelState.AddModelError("myfile", ex.Message);
					ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", vm.CategoryId);
					return View(vm);
				}
			}
			vm.MealsImage = mealInDb.MealsImage;

			if (ModelState.IsValid)
			{
				db.SaveChanges();
				return RedirectToAction("Index");
			}

			return View(vm);
		}


		//GET: Meals/Delete/5
		[Authorize]
		public ActionResult Delete(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Meal meal = db.Meals.Find(id);
			if (meal == null)
			{
				return HttpNotFound();
			}
			var vm = new MealIndexVM
			{
				Id = meal.Id,
				CategoryId = meal.CategoryId,
				Name = meal.Name,
				Description = meal.Description,
				Price = meal.Price,
				MealsImage = meal.MealsImage,
				Status = meal.Status,
				CreatedDate = meal.CreatedDate,
				ModifiedDate = meal.ModifiedDate,
			};
			return View(vm);
		}

		//POST: Meals/Delete/5
		[HttpPost, ActionName("Delete")]
		[ValidateAntiForgeryToken]
		public ActionResult DeleteConfirmed(int id)
		{
			Meal meal = db.Meals.Find(id);
			db.Meals.Remove(meal);
			db.SaveChanges();
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}
	}
}

RestaurantBackendWebsite/Views/Meals/Create.cshtml
@model RestaurantBackendWebsite.Models.ViewModels.MealIndexVM

@{
    ViewBag.Title = "新增餐點";
}

<h2>新增餐點</h2>


@using (Html.BeginForm("Create", "Meals", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="mb-3">
            @Html.LabelFor(model => model.CategoryName, "類別", htmlAttributes: new { @class = "form-label col-md-2" })
            @Html.DropDownList("CategoryId", ViewBag.CategoryId as SelectList, "請選擇", new { @class = " form-select" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })

        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-label col-md-2" })
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "form-label col-md-2" })
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "form-label col-md-2" })
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })

        </div>

        <div class="mb-3">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">上下架狀態</label>
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="mb-3">
            <label for="formFile" class="form-label">餐點照片</label>
            <input class="form-control" type="file" name="myfile" id="formFile">
            @Html.ValidationMessage("myfile", "", new { @class = "text-danger" })
        </div>

    </div>

    <div class="mb-3 text-end">
        <div class="text-end">
            <input type="submit" value="新增" class="btn btn-primary" />
            @Html.ActionLink("回到餐點清單頁", "Index", null, new { @class = "btn btn-success" })

        </div>
    </div>

}

<div>

</div>
@*@Styles.Render("~/Content/Meals.css")*@

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="path/to/jquery.validate.js"></script>

    @Scripts.Render("~/bundles/jqueryval")
}

RestaurantBackendWebsite/Views/Meals/Delete.cshtml
@model RestaurantBackendWebsite.Models.ViewModels.MealIndexVM

@{
    ViewBag.Title = "刪除餐點";
}

<h2>刪除餐點</h2>

@*<h3>你確定要刪除嗎?</h3>*@

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MealsImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MealsImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDate)
        </dd>

    </dl>

    @using (Html.BeginForm("Delete", "Meals", FormMethod.Post, new { id = "form1" }))
    {

        @Html.AntiForgeryToken()

        <div class="form-actions no-color text-end ">
            <input onclick="showAlert()" type="button" value="刪除" class="btn btn-primary" />
            @Html.ActionLink("回到餐點清單頁", "Index", null, new { @class = "btn btn-success" })
        </div>
    }
</div>
@section css {
    <style>
        .alert {
            height: 65px;
        }
    </style>
}
@section scripts {
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        const showAlert = () => {
            Swal.fire({
                title: '你確定嗎?',
                text: "您將無法恢復此筆餐點資料!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: '是的，確定刪除!',
                cancelButtonText: '取消'
            }).then((result) => {
                if (result.isConfirmed) {

                    var form = document.getElementById("form1");
                    form.submit();

                }
            });
        }

    </script>
}

RestaurantBackendWebsite/Views/Meals/Edit.cshtml
@model RestaurantBackendWebsite.Models.ViewModels.MealIndexVM

@{
    ViewBag.Title = "修改餐點";
}

<h2>修改餐點</h2>


@using (Html.BeginForm("Edit", "Meals", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="mb-3">
            @Html.LabelFor(model => model.CategoryName, "類別", htmlAttributes: new { @class = "form-label col-md-2" })
            @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = " form-select" })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "form-label col-md-2" })

            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })

        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "form-label col-md-2" })

            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })

        </div>

        <div class="mb-3">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "form-label col-md-2" })

            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })

        </div>


        <div class="mb-3">
            <div class="form-check">
                @Html.CheckBoxFor(model => model.Status, new { @class = "form-check-input", id = "flexCheckDefault" })
                <label class="form-check-label" for="flexCheckDefault">上下架狀態</label>
            </div>
        </div>

        <div class="mb-3">
            <label for="formFile" class="form-label">餐點照片</label>
            <input class="form-control" type="file" name="myfile" id="formFile">
            @Html.ValidationMessage("myfile", "", new { @class = "text-danger" })
            <p class="mt-3">圖片檔案:@Model.MealsImage</p>
        </div>


        <div class="mb-3">
            <div class="text-end">
                <input type="submit" value="存檔" class="btn btn-primary" />
                @Html.ActionLink("回到餐點清單頁", "Index", null, new { @class = "btn btn-success" })
            </div>
        </div>
    </div>
}

<div>

</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script>
        // 在檔案選擇後更新文本框的值
        document.getElementById("formFile").addEventListener("change", function () {
            var fileName = this.files[0].name;
            document.getElementById("fileName").value = fileName;
        });
    </script>
}

RestaurantBackendWebsite/Views/Meals/Index.cshtml
@using RestaurantBackendWebsite.Repositories;
@model IEnumerable<RestaurantBackendWebsite.Models.ViewModels.MealIndexVM>

@{
    ViewBag.Title = "維護餐點清單";
}

<h2>維護餐點清單</h2>

<form method="get">
    餐點名稱 :<input type="text" name="name" class="form-control form-control-sm" style="display:inline-block;" value="@(ViewBag.criteria)" />
    <input type="submit" name="btn" id="btn" value="搜尋" class="btn btn-sm btn-success" style="display: inline-block;">
    <input type="reset" name="btn" id="btn" value="重置" class="btn btn-sm btn-success" style="display: inline-block;">
</form>

<p class="new-meals">
    @Html.ActionLink("新增餐點", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CategoryId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CreatedDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ModifiedDate)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Price)
            </td>

            <td class="text-center">
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td class="text-center">
                @Html.DisplayFor(modelItem => item.ModifiedDate)
            </td>
            <td class="options">
                <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-primary btn-sm">
                    <i class="glyphicon glyphicon-pencil"></i>
                    編輯
                </a>

                <a href="@Url.Action("Delete", new { id = item.Id })" class="btn btn-danger btn-sm">
                    <i class="glyphicon glyphicon-trash"></i>
                    刪除
                </a>

            </td>
        </tr>
    }

</table>

<div class="container">
    <div class="row">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center" id="paginationBS5">
            </ul>
        </nav>
    </div>
</div>


@Styles.Render("~/Content/Meals.css")
@section scripts{
    <script src="/Scripts/WAPagination.js"></script>
    @{
        var paginationInfo = ViewBag.PaginationInfo as PaginationInfo;
        <div>total:@paginationInfo.Total</div>
    }
    <script>
        let current = @(paginationInfo.PageIndex);
        let pageSize = @(paginationInfo.PageSize);
        let showPages = 5;
        let total = @(paginationInfo.Total);

        let options = Pagination.getDefaultOptions();
        options.total = total;
        options.current = current;
        options.pageSize = pageSize;
        options.showPages = showPages;
        options.containerSelector = "#paginationBS5";

        options.urlTemplate = `/Meals/Index?name=@(ViewBag.criteria)&pageIndex={page}&pageSize=${options.pageSize}`;
        let pagination = new Pagination().render(options);


    </script>
}